// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrunStok1.Data;

namespace UrunStok1.Migrations
{
    [DbContext(typeof(UrunDbContext))]
    partial class UrunDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("UrunStok1.Data.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<int>("Stok")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urun");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Aciklama = "Oyun bilgisayarı",
                            Fiyat = 10000.0,
                            Stok = 20,
                            UrunAdi = "Laptop"
                        },
                        new
                        {
                            Id = 1002,
                            Aciklama = "Office Application",
                            Fiyat = 500.0,
                            Stok = 99,
                            UrunAdi = "Microsoft Office"
                        },
                        new
                        {
                            Id = 1003,
                            Aciklama = " ",
                            Fiyat = 2000.0,
                            Stok = 12,
                            UrunAdi = "Lazer Mouse"
                        },
                        new
                        {
                            Id = 1004,
                            Aciklama = "64GB",
                            Fiyat = 200.0,
                            Stok = 5,
                            UrunAdi = "USB Storage"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
